apiVersion: v1
kind: Service
metadata:
  name: api-echo
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: api-echo
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-echo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-echo
    spec:
      containers:
      # [START api]
      - name: api
        args:
        - gunicorn
        - -w
        - "1"
        - --chdir
        - /app
        - manage:app
        - -b
        - :8080
        - --name
        - app
        - --log-file=uni.log
        image: gcr.io/yolo-parking-pi/api:v1.0.1
        args: [
          "--http_port=8081",
          "--backend=127.0.0.1:8080",
          "--service=echo-api.endpoints.yolo-parking-pi.cloud.goog",
          "--rollout_strategy=managed"
        ]
      # [END api]
        ports:
        - containerPort: 8081
      - name: echo
        image: gcr.io/google-samples/echo-python:1.0
        ports:
        - containerPort: 8080
